---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: silverbullet
    includeTemplates: true
    includeSelectors: true
  - pairs:
      app.kubernetes.io/part-of: silverbullet
      app.kubernetes.io/managed-by: kustomize
    includeTemplates: true

namespace: silverbullet
resources:
  - namespace.yml
  - deployment.yml
  - service.yml
  - ingress.yml
  - pv.yml

images:
  - name: silverbullet
    newName: ghcr.io/silverbulletmd/silverbullet
    newTag: 2.4.1
