---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: mealie
    includeTemplates: true
    includeSelectors: true
  - pairs:
      app.kubernetes.io/part-of: mealie
      app.kubernetes.io/managed-by: kustomize
    includeTemplates: true

namespace: mealie
resources:
  - namespace.yml
  - deployment.yml
  - service.yml
  - ingress.yml
  - pv.yml

secretGenerator:
  - name: mealie-credentials
    options:
      disableNameSuffixHash: true
    envs:
      - mealie-credentials.env

images:
  - name: mealie
    newName: ghcr.io/mealie-recipes/mealie
    newTag: v3.9.2
