---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: minecraft-gtnh
    includeTemplates: true
    includeSelectors: true
  - pairs:
      app.kubernetes.io/part-of: minecraft-gtnh
      app.kubernetes.io/managed-by: kustomize
    includeTemplates: true

namespace: minecraft-gtnh
resources:
  - namespace.yml
  - pv.yml
  - deployment.yml
  - service.yml

configMapGenerator:
  - name: minecraft-gtnh-cm
    files:
      - whitelist.json=data/whitelist.json
      - ops.json=data/ops.json

images:
  - name: minecraft-gtnh
    newName: ghcr.io/istoleyurballs/minecraft-gtnh
    newTag: 2.8.4-java25-rev9
