---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: chart
spec:
  chart: oci://quay.io/jetstack/charts/cert-manager
  version: v1.19.3
  targetNamespace: cert-manager
  createNamespace: true
  valuesContent: |-
    crds:
      enabled: true

    resources:
      requests: { cpu: 10m, memory: 64Mi }
      limits: { cpu: 1000m, memory: 128Mi }
    cainjector:
      resources:
        requests: { cpu: 10m, memory: 64Mi }
        limits: { cpu: 1000m, memory: 128Mi }
    webhook:
      resources:
        requests: { cpu: 10m, memory: 64Mi }
        limits: { cpu: 1000m, memory: 128Mi }
