---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: jellyfin
      app.kubernetes.io/managed-by: kustomize
    includeTemplates: true

namespace: jellyfin
resources:
  - jellyfin
  - exporter

images:
  - name: jellyfin
    newName: ghcr.io/jellyfin/jellyfin
    newTag: 10.11.6
  - name: json-exporter
    newName: quay.io/prometheuscommunity/json-exporter
    newTag: v0.7.0
